#!/usr/bin/env php
<?php
require_once 'Interpreter.php';
require_once 'Environment.php';


$fileContent = file_get_contents($_SERVER['argv'][1]);
$env = new Environment();
$interpreter = new Interpreter($fileContent, $env);

$interpreter->evaluate();



